### ISSUE TITLE
Property group with underscore in name doesn't work

### ISSUE THREAD

**Issue by darkpaw** [npryce/konfig#10]
```
import com.natpryce.konfig.*
import org.junit.Test

class KonfigUnderscoreTest {

    object db_server : PropertyGroup() {
        val port by intType
        val host by stringType
    }

    val config = ConfigurationProperties.fromResource("db_server.properties")

    val port = config[db_server.port]
    val host = config[db_server.host]

    @Test
    fun konfig_test(){
        println("$host:$port")
    }

}

```

com.natpryce.konfig.Misconfiguration: db-server.port property not found; searched:
 - db-server.port in resource db_server.properties

It seems to silently convert underscores to dashes somewhere.

**Comment by npryce** [comment]
Yes.   This should be better documented.  

Konfig uses "-" to separate words within property levels, and "." to separate property levels.

It translates names in the code to that naming convention.  And also translates that naming convention to the naming conventions used by different configuration sources (e.g. it translates to upper-case names with underscores to look up environment variables).

**Comment by npryce** [comment]
Raised documentation issue #12
