### ISSUE TITLE
Support different file formats for config

### ISSUE THREAD

**Issue by ayrat555** [npryce/konfig#21]
Thank you for your hard work!

I have a question about supported config file format. Will it be possible to use format other than java properties format (yml etc)?

**Comment by uchuhimo** [comment]
[Konf](https://github.com/uchuhimo/konf) is a similar configuration library, which supports YAML and many other formats (JSON/HOCON/XML/TOML/etc). Give it a try.

**Comment by ayrat555** [comment]
@uchuhimo thank, I will try it. My colleague is already your library

**Comment by npryce** [comment]
You can write an implementation of the `Configuration` interface to read configuration from other sources.  On our project, for example, we have implementations that read from environment variables configured in CloudFoundry YAML manifests, from JSON objects, etc.
