### ISSUE TITLE
Add option to exclude underscore replacement 

### ISSUE THREAD

**Issue by dzastinas** [npryce/konfig#25]
Is it possible to add functionality to make this magic.kt test pass? I have some properties with key name '_' underscore.

From:

object a_group : PropertyGroup() {
        val a_property by stringType
    }

@Test
    fun underscore_not_replaced_with_hyphen() {
        assertThat(a_group.a_property.name, equalTo("a_group.a_property"))
    }

magic.kt:23

**Comment by npryce** [comment]
See comments in #27.  I'll add this to the README.

**Comment by npryce** [comment]
Covered by #12

**Comment by npryce** [comment]
Documented more thoroughly in the README
