### ISSUE TITLE
Invalid version uploaded to MavenCentral

### ISSUE THREAD

**Issue by czyzby** [npryce/konfig#28]
It seems that `version=1.6.2.1` was uploaded by mistake. See http://mvnrepository.com/artifact/com.natpryce/konfig

**Comment by markjfisher** [comment]
This is a duplicate of #16 - Unfortunately still not fixed.
This works in the mean time:

    compile 'com.natpryce:konfig:version=1.6.2.1'

**Comment by czyzby** [comment]
I think you can push `1.6.2.1` as a separate artifact, it should not collide with `version=1.6.2.1` on Maven Central. Try contacting the support, so they can remove the broken release.

Anyway, since this is a duplicate, I'm closing the issue.
